import KLAPCore
import Foundation
import CoreGraphics
func expect(_ condition: @autoclosure () -> Bool, _ message: String) {
    guard condition() else { fatalError(message) }
}
expect(StudyProgress(percent: -2, current: -1, total: -1) == StudyProgress(percent: 0, current: 0, total: 0), "Negative values")
expect(StudyProgress(percent: 150, current: 9, total: 3).fraction == 1, "Upper bound")
expect(StudyProgress(percent: .nan, current: 1, total: 3).fraction == 0, "NaN")
expect(StudyProgress(percent: .infinity, current: 1, total: 3).fraction == 0, "Infinity")
expect(StudyProgress(percent: 35, current: 2, total: 5).label == "2/5", "Queue position")
expect(StudyProgress(percent: 0, current: 1, total: 0).label == "", "Empty queue")
expect(StudyProgress(percent: 0, current: 8, total: 5).label == "5/5", "Queue clamp")
expect(StudyProgress(percent: -Double.infinity, current: -4, total: 5) == StudyProgress(percent: 0, current: 0, total: 5), "Negative infinity and negative queue position")
expect(StudyProgress(percent: Double.infinity, current: 5, total: 5).fraction == 0, "Positive infinity")
expect(StudyProgress(percent: 100, current: 5, total: 5).label == "5/5", "Completed queue")
expect(StudyProgress(percent: 50, current: 1, total: 0).label.isEmpty, "Nonempty position with empty queue")
print("11 progress checks passed")
expect(TimetableClock.minutes(period: -1, span: 1) == nil, "Negative period")
expect(TimetableClock.minutes(period: 1, span: 0) == nil, "Invalid span")
expect(TimetableClock.minutes(period: 11, span: 2) == nil, "Overflow period")
expect(TimetableClock.minutes(period: 0, span: 2)?.end == 590, "Special consecutive class")
expect(TimetableClock.minutes(period: 6, span: 3)?.end == 1155, "Evening consecutive class")
expect(TimetableClock.minutes(period: 11, span: 1)?.end == 1325, "Night class")
expect(DestinationPolicy.uniqueNames(["A","A","B"," "]) == ["B"], "Ambiguous destinations")
expect(DestinationPolicy.uniqueNames([]).isEmpty, "Empty destinations")
expect(DestinationPolicy.availableName("KLAP",existing:["KLAP","KLAP (2)"]) == "KLAP (3)", "New destination collisions")
expect(DestinationPolicy.availableName("KLAP",existing:[]) == "KLAP", "First destination")
expect(TimetableClock.minutes(period: 0,span: 12)?.end == 1325, "A full-day span stays inside available periods")
expect(TimetableClock.minutes(period: 1,span: 12) == nil, "Span past final period")
expect(TimetableClock.minutes(period: 12,span: 1) == nil, "Period after final period")
expect(DestinationPolicy.uniqueNames([" A ","A","\n","A"]) == [" A "], "Exact duplicate count and whitespace-only names")
expect(DestinationPolicy.availableName("KLAP",existing:["KLAP","KLAP (2)","KLAP (4)"]) == "KLAP (3)", "First available suffix after gaps")
print("15 timetable and destination checks passed")

let selectedDestinations=DestinationConfiguration(
    timetable:"개인 캘린더 🚀",academic:"",reminder:"마감/할 일",
    newTimetable:"새 시간표",newAcademic:"KLAP 학사일정",newReminder:"새 할 일"
)
expect(selectedDestinations.timetable=="개인 캘린더 🚀" && selectedDestinations.academic=="KLAP 학사일정" && selectedDestinations.reminder=="마감/할 일","Selected and newly named destinations resolve independently")
expect(selectedDestinations.usesExistingTimetable && !selectedDestinations.usesExistingAcademic && selectedDestinations.usesExistingReminder,"Bridge existing-list flags match each resolved choice")
let requestData=try JSONSerialization.data(withJSONObject:selectedDestinations.bridgeRequest)
let requestObject=try JSONSerialization.jsonObject(with:requestData) as! [String:Any]
expect(requestObject["TimetableName"] as? String=="개인 캘린더 🚀" && requestObject["AcademicExisting"] as? Bool==false,"Destination request is valid JSON and preserves Unicode names")
let defaultDestinations=DestinationConfiguration(timetable:"",academic:"",reminder:"",newTimetable:"시간표 2",newAcademic:"학사 일정",newReminder:"미리 알림")
expect(defaultDestinations.bridgeRequest.values.count==6 && !defaultDestinations.usesExistingTimetable && !defaultDestinations.usesExistingAcademic && !defaultDestinations.usesExistingReminder,"New destination request contains all names and marks each as new")
let destinationSuite="KLAP.destinations."+UUID().uuidString
let destinationDefaults=UserDefaults(suiteName:destinationSuite)!
selectedDestinations.persist(in:destinationDefaults)
expect(destinationDefaults.bool(forKey:"destinationsConfigured") && destinationDefaults.string(forKey:"destinationTimetable")==selectedDestinations.timetable && destinationDefaults.string(forKey:"destinationAcademic")==selectedDestinations.academic && destinationDefaults.string(forKey:"destinationReminder")==selectedDestinations.reminder,"Persisted destination names match the bridge configuration")
defaultDestinations.persist(in:destinationDefaults)
expect(destinationDefaults.string(forKey:"destinationTimetable")=="시간표 2" && destinationDefaults.string(forKey:"destinationAcademic")=="학사 일정" && destinationDefaults.string(forKey:"destinationReminder")=="미리 알림","Saving new names replaces the prior saved selection")
destinationDefaults.removePersistentDomain(forName:destinationSuite)
print("5 destination request and persistence checks passed")

func makeEntry(_ period:Int, _ span:Int=1, day:Int=1, online:Bool=false) throws -> TimetableEntry {
    let data=try JSONSerialization.data(withJSONObject:["SubjectID":"course", "SubjectName":"과목", "Weekday":day, "Period":period, "Span":span, "Room":"101", "Online":online])
    return try JSONDecoder().decode(TimetableEntry.self,from:data)
}
let layout=TimetableClock.placements(try [makeEntry(0),makeEntry(1),makeEntry(2)])
expect(layout.map(\.lane) == [0,1,1], "Overlapping intervals reuse only free lanes")
expect(layout.allSatisfy{$0.laneCount == 2}, "Consistent overlapping lane widths")
let excluded = try [makeEntry(1,day:0),makeEntry(2,online:true)]
expect(TimetableClock.placements(excluded).isEmpty,"Unknown and online classes excluded from grid")
let empty=try JSONDecoder().decode(Snapshot.self,from:Data("{\"timetable\":null,\"lectures\":null,\"errors\":[]}".utf8))
expect(empty.lectures == nil && empty.errors.isEmpty,"Nullable CLI collections")
let nested=TimetableClock.placements(try [makeEntry(0,4),makeEntry(1,4),makeEntry(2),makeEntry(4)])
expect(nested.map(\.lane) == [0,1,2,0], "Nested overlaps reuse only lanes whose intervals ended")
expect(nested.allSatisfy{$0.laneCount == 3}, "Overlapping layout assigns a common lane count")
let independent=TimetableClock.placements(try [makeEntry(1,day:1),makeEntry(1,day:2)])
expect(independent.count == 2 && independent.allSatisfy{$0.lane == 0 && $0.laneCount == 1}, "Different weekdays have independent lanes")
do {
    _ = try JSONDecoder().decode(Snapshot.self,from:Data("{broken".utf8))
    fatalError("Malformed snapshot JSON must fail")
} catch {}
print("8 layout and decoding checks passed")
let screen = CGRect(x:0,y:0,width:1440,height:875)
let rightPanel=MenuPanelPlacement.frame(anchor:CGRect(x:1410,y:875,width:24,height:25),visibleScreen:screen,size:CGSize(width:540,height:700))
expect(screen.contains(rightPanel) && rightPanel.maxX == 1432, "Panel remains inside right edge")
let leftScreen=CGRect(x:-1920,y:0,width:1920,height:1055)
let leftPanel=MenuPanelPlacement.frame(anchor:CGRect(x:-1910,y:1055,width:24,height:25),visibleScreen:leftScreen,size:CGSize(width:540,height:700))
expect(leftScreen.contains(leftPanel) && leftPanel.minX == -1912,"Secondary monitor with negative origin")
let smallScreen=CGRect(x:0,y:0,width:500,height:600)
let smallPanel=MenuPanelPlacement.frame(anchor:CGRect(x:250,y:600,width:24,height:25),visibleScreen:smallScreen,size:CGSize(width:540,height:700))
expect(smallScreen.contains(smallPanel),"Small screen bounds")
let oversizedPanel=MenuPanelPlacement.frame(anchor:CGRect(x:250,y:600,width:24,height:25),visibleScreen:smallScreen,size:CGSize(width:900,height:900))
expect(smallScreen.contains(oversizedPanel) && oversizedPanel.width == 484 && oversizedPanel.height == 584,"Panel larger than screen is clamped to visible bounds")
expect(!MenuPanelPlacement.validAnchor(CGRect(x:CGFloat.infinity,y:875,width:24,height:25),screen:fullScreen),"Infinite anchor rejected")
expect(!MenuPanelPlacement.validAnchor(CGRect(x:1200,y:875,width:0,height:25),screen:fullScreen),"Zero-width anchor rejected")
print("6 panel positioning checks passed")

expect(StudyTime(achieved:"5",required:"20").remaining == 15,"Remaining minutes")
expect(StudyTime(achieved:"30",required:"20").remaining == 0,"Over-completed clamp")
expect(StudyTime(achieved:nil,required:"20").remaining == nil,"Unknown achieved")
expect(StudyTime(achieved:"NaN",required:"20").remaining == nil,"Invalid achieved")
expect(StudyTime(achieved:"2",required:"0").remaining == nil,"Unknown duration")
expect(StudyTime(achieved:"-1",required:"20").remaining == nil,"Negative achieved")
expect(StudyTime.minutes(0.5) == "1분","Round remaining up")
expect(StudyTime(achieved:" 2.5 ",required:" 3.5 ").remaining == 1,"Trim fractional time values")
expect(StudyTime(achieved:"1",required:"NaN").remaining == nil,"Reject NaN required duration")
expect(StudyTime(achieved:"1",required:"infinity").remaining == nil,"Reject infinite required duration")
expect(StudyTime.minutes(-0.2) == "0분","Negative display duration clamps to zero")
expect(StudyTime.minutes(nil) == "확인 중","Unknown display duration")
print("12 study time checks passed")

let reminderNote="--- KLAP ---\nID: lecture:abc\n[This reminder is created by KLAP.]"
expect(ReminderIdentity.matches(notes:reminderNote,lectureID:"abc"),"Exact lecture ID")
expect(ReminderIdentity.matches(notes:reminderNote,lectureID:"lecture:abc"),"Prefixed lecture ID")
expect(!ReminderIdentity.matches(notes:reminderNote,lectureID:"ab"),"No prefix collision")
expect(!ReminderIdentity.matches(notes:"ID: lecture:abc",lectureID:"abc"),"No unowned reminder")
expect(!ReminderIdentity.matches(notes:nil,lectureID:"abc"),"Missing metadata")
expect(!ReminderIdentity.matches(notes:reminderNote,lectureID:""),"Empty identity")
expect(!ReminderIdentity.matches(notes:"--- KLAP ---\nID: lecture:abc",lectureID:"abc"),"Metadata without closing footer is not owned")
expect(!ReminderIdentity.matches(notes:"--- KLAP ---\n[This reminder is created by KLAP.]\nID: lecture:abc",lectureID:"abc"),"Metadata after the ownership footer is ignored")
expect(!ReminderIdentity.matches(notes:"--- KLAP ---\nID: lecture:abc\n[This reminder is created by KLAP.]",lectureID:"ABC"),"Identity matching is exact")
expect(ReminderIdentity.matches(notes:"teacher note\n--- KLAP ---\nID: lecture:abc\n[This reminder is created by KLAP.]",lectureID:"abc"),"User notes before the ownership header do not change identity")
print("10 reminder identity checks passed")

let fullScreen=CGRect(x:0,y:0,width:1440,height:900)
expect(!MenuPanelPlacement.validAnchor(.zero,screen:fullScreen),"Unlaid status item")
expect(!MenuPanelPlacement.validAnchor(CGRect(x:0,y:0,width:24,height:24),screen:fullScreen),"Temporary origin rejected")
expect(MenuPanelPlacement.validAnchor(CGRect(x:1200,y:875,width:24,height:25),screen:fullScreen),"Menu bar anchor accepted")
expect(MenuPanelPlacement.validAnchor(CGRect(x:-1200,y:875,width:24,height:25),screen:CGRect(x:-1440,y:0,width:1440,height:900)),"Negative screen anchor accepted")
expect(!MenuPanelPlacement.validAnchor(CGRect(x:1600,y:875,width:24,height:25),screen:fullScreen),"Wrong screen rejected")
print("5 startup anchor checks passed")

let tones=CourseTones.assign(["a","b","c","d","e","a"])
expect(tones.count == 5 && Set(tones.values).count == 5,"Distinct tones for five courses")
expect(tones == CourseTones.assign(["e","d","c","b","a"]),"Stable order and repeated meetings")
expect(CourseTones.assign([]).isEmpty,"Empty course palette")
expect(CourseTones.assign(["one"])["one"] == 50,"Single course seed")
expect(Set(CourseTones.assign((0..<20).map(String.init)).values).count == 20,"No modulo palette collisions")
let manyCourseIDs=(0..<500).map{"course-\($0)"}
let manyTones=CourseTones.assign(manyCourseIDs)
expect(manyTones.count == 500 && manyTones.values.allSatisfy{$0 >= 15 && $0 <= 80},"Large course sets remain in the usable tonal range")
expect(manyTones == CourseTones.assign(Array(manyCourseIDs.reversed())),"Large course sets are independent of input order")
let orderedTones=manyTones.keys.sorted().compactMap{manyTones[$0]}
expect(zip(orderedTones,orderedTones.dropFirst()).allSatisfy{$0 < $1},"Course tones are strictly increasing and distinct")
print("8 course tone checks passed")

let deadline=Date(timeIntervalSince1970:100000)
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:nil,finished:deadline,now:deadline) == .complete,"Completed at deadline")
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:deadline.addingTimeInterval(-1),finished:deadline.addingTimeInterval(1),now:deadline) == .late,"Crossed deadline")
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:nil,finished:nil,now:deadline.addingTimeInterval(1)) == .unknown,"No invented completion time")
expect(LectureStatus.resolve(complete:false,deadline:deadline,started:nil,finished:nil,now:deadline.addingTimeInterval(1)) == .missed,"Expired incomplete")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-18000)) == 2,"Five hours red")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-86400)) == 1,"One day orange")
expect(LectureStatus.resolve(complete:false,deadline:deadline,started:nil,finished:nil,now:deadline) == .pending,"Incomplete at deadline remains pending")
expect(LectureStatus.resolve(complete:false,deadline:deadline,started:nil,finished:nil,now:deadline.addingTimeInterval(0.001)) == .missed,"Incomplete just after deadline is missed")
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:nil,finished:deadline,now:deadline.addingTimeInterval(10)) == .complete,"Finished exactly at deadline is on time")
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:deadline,finished:deadline.addingTimeInterval(1),now:deadline) == .unknown,"Start exactly at deadline does not imply late")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-5*3600)) == 2,"Five-hour urgency boundary is inclusive")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-5*3600-1)) == 1,"Just outside five-hour boundary")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-24*3600)) == 1,"Twenty-four-hour urgency boundary is inclusive")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-24*3600-1)) == 0,"Just outside one-day boundary")
expect(LectureStatus.date("not-a-date") == nil && LectureStatus.date("") == nil,"Malformed and empty server dates")
print("14 lecture status checks passed")

let serverLecture = try JSONDecoder().decode(Lecture.self,from:Data(#"{"Title":"sample","Progress":"100","FirstStartedAt":"2026-09-01T15:01:00+09:00","FirstCompletedAt":"2026-09-01T16:33:00+09:00","AchievedTime":"41","RequiredTime":"41","EndAt":"2026-09-14T23:59:00+09:00"}"#.utf8))
expect(LectureStatus.date(serverLecture.FirstStartedAt) != nil && LectureStatus.date(serverLecture.FirstCompletedAt) != nil,"CLI server timestamps decode")
let legacyLecture=try JSONDecoder().decode(Lecture.self,from:Data(#"{"Title":"sample","Progress":"0"}"#.utf8))
expect(legacyLecture.FirstStartedAt == nil && legacyLecture.FirstCompletedAt == nil,"Older cache timestamps unknown")
expect(LectureStatus.date("2026-09-01T15:01:00.123+09:00") != nil,"Fractional seconds with timezone decode")
print("4 CLI timestamp contract checks passed")

let periodRows=TimetableClock.placements(try [makeEntry(1),makeEntry(1,2),makeEntry(3)],byPeriod:true)
expect(periodRows.map(\.start) == [1,1,3],"Period grid starts")
expect(periodRows.map(\.end) == [2,3,4],"Period spans preserved")
expect(periodRows.map(\.lane) == [0,1,0],"Period overlaps and adjacency")
let nightRows=TimetableClock.placements(try [makeEntry(11)],byPeriod:true)
expect(nightRows.first?.end == 12,"Last period boundary")
let onlineRows=TimetableClock.placements(try [makeEntry(1,online:true)],byPeriod:true)
expect(onlineRows.isEmpty,"Online outside period grid")
print("5 period grid checks passed")
let minimalNotice = try JSONDecoder().decode(Notice.self, from: Data(#"{"Title":"공지"}"#.utf8))
expect(minimalNotice.Registered == nil && minimalNotice.Top == nil, "Older notice metadata")
let emptyNotice = try JSONDecoder().decode(NoticeDetailResult.self, from: Data(#"{"ID":"n","DetailURL":"https://klas.kw.ac.kr/","Detail":{"Title":"공지","ContentText":"","Registered":null,"Attachment":null}}"#.utf8))
expect(emptyNotice.Detail.ContentText.isEmpty && emptyNotice.Detail.Attachment == nil, "Empty notice body and null attachment")
print("2 notice contract checks passed")
expect(GradeAllocation(count:0) == nil && GradeAllocation(count:-1) == nil, "Unknown or empty enrollment")
let allocation107 = GradeAllocation(count:107)!
expect(allocation107.a == 42 && allocation107.b == 43 && allocation107.lower == 22, "Noncumulative grade example")
for count in Array(1...512) + [Int.max] {
    let value = GradeAllocation(count:count)!
    expect(value.a + value.b + value.lower == count, "Allocation conserves enrollment")
    expect(value.a >= 0 && value.b >= 0 && value.lower >= 0, "Allocation nonnegative")
    expect(value.a <= count/2 && value.a+value.b <= count, "Allocation stays nonnegative and within enrollment")
}
print("1 example and 513 grade allocation edge checks passed")

let previewTestRoot=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
defer { try? FileManager.default.removeItem(at:previewTestRoot) }
let previewRoot=previewTestRoot.appendingPathComponent("cache")
let downloadsRoot=previewTestRoot.appendingPathComponent("downloads")
let baseDate=Date()
var store=try PreviewFileStore(root:previewRoot,now:baseDate)
func samplePreview(_ name:String) throws -> URL {
    let folder=previewRoot.appendingPathComponent("attachment-"+UUID().uuidString)
    try FileManager.default.createDirectory(at:folder,withIntermediateDirectories:true)
    let file=folder.appendingPathComponent(name); try Data("PDF".utf8).write(to:file); return file
}
let first=try samplePreview("자료.pdf")
try store.register(first,key:"one",now:baseDate)
try store.opened("one")
try store.cleanup(now:baseDate.addingTimeInterval(20000))
expect(FileManager.default.fileExists(atPath:first.path),"Open preview never expires")
try store.closed("one",now:baseDate)
try store.cleanup(now:baseDate.addingTimeInterval(10799))
expect(FileManager.default.fileExists(atPath:first.path),"Preserve before three hours")
try store.cleanup(now:baseDate.addingTimeInterval(10800))
expect(!FileManager.default.fileExists(atPath:first.path),"Delete at three hours")
let second=try samplePreview("資料.pdf")
try store.register(second,key:"two",now:baseDate)
store=try PreviewFileStore(root:previewRoot,now:baseDate.addingTimeInterval(100))
let cachedSecond = try store.cached("two",now:baseDate.addingTimeInterval(100))
expect(cachedSecond == second,"Persist cache across launch")
try FileManager.default.createDirectory(at:downloadsRoot,withIntermediateDirectories:true)
try Data("existing".utf8).write(to:downloadsRoot.appendingPathComponent("資料.pdf"))
let saved=try store.moveToDownloads("two",directory:downloadsRoot,now:baseDate.addingTimeInterval(100))
expect(saved.lastPathComponent == "資料 (1).pdf","Preserve duplicate filename")
expect(!FileManager.default.fileExists(atPath:second.path),"Move instead of copy")
try store.cleanup(now:baseDate.addingTimeInterval(30000))
expect(FileManager.default.fileExists(atPath:saved.path),"Downloads excluded from cleanup")
let originalDownload = try Data(contentsOf:downloadsRoot.appendingPathComponent("資料.pdf"))
expect(originalDownload == Data("existing".utf8),"Existing download unchanged")
let third=try samplePreview("image.png")
try store.register(third,key:"three",now:baseDate)
try store.opened("three"); try store.closed("three",now:baseDate)
try store.opened("three"); try store.closed("three",now:baseDate.addingTimeInterval(1000))
try store.cleanup(now:baseDate.addingTimeInterval(10800))
expect(FileManager.default.fileExists(atPath:third.path),"Reopen resets close deadline")
store=try PreviewFileStore(root:previewRoot,now:baseDate.addingTimeInterval(11800))
expect(!FileManager.default.fileExists(atPath:third.path),"Expired cache cleaned on launch")
do { try store.register(saved,key:"outside"); fatalError("Accepted external file") } catch { }
print("11 preview file lifecycle checks passed")

let custodyRoot=FileManager.default.temporaryDirectory.appendingPathComponent("klap-preview-custody-"+UUID().uuidString)
defer {try? FileManager.default.removeItem(at:custodyRoot)}
let custodyCache=custodyRoot.appendingPathComponent("cache")
let unrelatedFile=custodyRoot.appendingPathComponent("user-data.txt")
try FileManager.default.createDirectory(at:custodyCache,withIntermediateDirectories:true)
try Data("user-owned".utf8).write(to:unrelatedFile)
let forgedManifest=try JSONSerialization.data(withJSONObject:["forged":["path":unrelatedFile.path,"expires":0]])
try forgedManifest.write(to:custodyCache.appendingPathComponent("manifest.json"))
_ = try PreviewFileStore(root:custodyCache,now:baseDate)
let afterManifestRecovery=try Data(contentsOf:unrelatedFile)
expect(afterManifestRecovery==Data("user-owned".utf8),"A forged cache manifest cannot delete a file outside the preview root")
let cacheFolder=custodyCache.appendingPathComponent("attachment-forged")
try FileManager.default.createDirectory(at:cacheFolder,withIntermediateDirectories:true)
let symlink=cacheFolder.appendingPathComponent("linked.txt")
try FileManager.default.createSymbolicLink(at:symlink,withDestinationURL:unrelatedFile)
let guardedStore=try PreviewFileStore(root:custodyCache,now:baseDate)
do {try guardedStore.register(symlink,key:"symlink",now:baseDate);fatalError("A symlink to a user file must not be owned") } catch {}
let afterSymlinkRejection=try Data(contentsOf:unrelatedFile)
expect(afterSymlinkRejection==Data("user-owned".utf8),"Rejected symlink registration preserves the target")
print("2 preview cache custody and symlink checks passed")

let linkedText="한글 안내 👋\nhttps://discord.gg/3vv49s3UJ\n자세한 내용: (https://example.org/docs?q=1&lang=ko)."
let linked=LinkedBody.attributed(linkedText)
let urls=linked.runs.compactMap { $0.link?.absoluteString }
expect(String(linked.characters)==linkedText,"Link detection preserves Korean, emoji and line breaks")
expect(urls==["https://discord.gg/3vv49s3UJ","https://example.org/docs?q=1&lang=ko"],"Detect URLs without surrounding punctuation")
expect(LinkedBody.attributed("").runs.compactMap(\.link).isEmpty,"Empty body")
expect(LinkedBody.attributed("일반 공지입니다").runs.compactMap(\.link).isEmpty,"Plain body")
expect(LinkedBody.attributed("javascript:alert(1) file:///tmp/a").runs.compactMap(\.link).isEmpty,"Do not make executable or local URLs clickable")
print("5 body link checks passed")

let memory=MemoryPreviewStore(limit:8)
try memory.register(Data([1,2,3,4]),name:"../sample.pdf",key:"one")
memory.opened("one")
try memory.register(Data([5,6,7,8]),name:"sample.pdf",key:"two")
try memory.register(Data([9,10,11,12]),name:"sample.pdf",key:"three")
expect(memory.cached("one") != nil && memory.cached("two")==nil,"Eviction protects open previews")
do {try memory.register(Data(repeating:0,count:9),name:"large",key:"large");fatalError("Accepted oversized preview")} catch {}
expect(memory.byteCount==8,"Oversize rejection preserves cache")
let memoryDownloads=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
defer {try? FileManager.default.removeItem(at:memoryDownloads)}
let memoryFirst=try memory.save("one",to:memoryDownloads)
let memorySecond=try memory.save("three",to:memoryDownloads)
expect(memoryFirst.lastPathComponent=="sample.pdf" && memorySecond.lastPathComponent=="sample (1).pdf","Sanitize paths and preserve duplicate downloads")
let memorySavedBytes=try Data(contentsOf:memoryFirst)
expect(memorySavedBytes==Data([1,2,3,4]),"Downloaded bytes unchanged")
expect(memory.byteCount==0,"Download releases cached data")
try memory.register(Data([1]),name:"expiry",key:"expiry",now:baseDate)
memory.opened("expiry")
memory.cleanup(now:baseDate.addingTimeInterval(20000))
expect(memory.cached("expiry") != nil,"Open preview does not expire")
memory.closed("expiry",now:baseDate)
memory.cleanup(now:baseDate.addingTimeInterval(10800))
expect(memory.cached("expiry")==nil,"Closed preview expires after three hours")
print("7 memory preview checks passed")

let protectedMemory=MemoryPreviewStore(limit:8)
try protectedMemory.register(Data([1,2,3,4]),name:"one.bin",key:"one",now:baseDate)
protectedMemory.opened("one")
try protectedMemory.register(Data([5,6,7,8]),name:"two.bin",key:"two",now:baseDate)
protectedMemory.opened("two")
do {try protectedMemory.register(Data(repeating:9,count:7),name:"replacement.bin",key:"one",now:baseDate.addingTimeInterval(1));fatalError("An oversized replacement must fail while all other cache entries are open")} catch {}
expect(protectedMemory.cached("one")?.data==Data([1,2,3,4]) && protectedMemory.cached("two")?.data==Data([5,6,7,8]),"Failed replacement restores the previous item and preserves open previews")
expect(protectedMemory.byteCount==8,"Failed replacement restores the memory byte count")
let blockedDownloads=memoryDownloads.appendingPathComponent("not-a-directory")
try Data("block".utf8).write(to:blockedDownloads)
try memory.register(Data([8,9]),name:"retry.bin",key:"retry",now:baseDate)
do {_ = try memory.save("retry",to:blockedDownloads);fatalError("Download into a regular file must fail")} catch {}
expect(memory.cached("retry")?.data==Data([8,9]),"Failed save keeps the cached preview available for retry")
print("10 memory preview capacity, replacement and retry checks passed")

func contentID(_ kind:String,_ course:String,_ remote:String,_ term:String="2026,2")->String {
    let fields=[term,course,remote]+(kind=="notice" ? ["master"] : [])
    return ([kind,"v1"]+fields.map{Data($0.utf8).base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"")}).joined(separator:":")
}
func notificationSnapshot(account:String="account-a",term:String="2026,2",courses:[String]=["c1"],noticeIDs:[String]?=[],lectureIDs:[String]?=[],blocked:Set<String>=[])->Snapshot {
    var json:[String:Any]=["account":account,"errors":[],"timetable":["Term":["value":term,"label":term,"subjList":courses.map{["name":$0,"value":$0]}]]]
    if let noticeIDs {json["notices"]=noticeIDs.map{["ID":$0,"CourseName":ContentAddress($0)?.course ?? "c1","Notice":["Title":$0]] as [String:Any]}}
    if let lectureIDs {json["lectures"]=lectureIDs.map{["row":["ID":$0,"CourseName":ContentAddress($0)?.course ?? "c1","Lecture":["Title":$0,"Progress":"0"]],"reason":blocked.contains($0) ? "closed" : ""] as [String:Any]}}
    return try! JSONDecoder().decode(Snapshot.self,from:JSONSerialization.data(withJSONObject:json))
}
let n1=contentID("notice","c1","1"),n2=contentID("notice","c1","2")
let l1=contentID("lecture","c1","1"),l2=contentID("lecture","c1","2")
var history=ContentNotificationHistory()
history.ingest(notificationSnapshot(noticeIDs:[n1],lectureIDs:[l1]),notices:true,lectures:true)
expect(history.alerts.isEmpty,"Initial lists are baseline only")
history.ingest(notificationSnapshot(noticeIDs:[n1,n2],lectureIDs:[l1,l2]),notices:true,lectures:true)
expect(history.alerts.count==2,"New notice and lecture produce separate alerts")
let lectureAlert=history.alerts.first{$0.kind == .lecture}!
expect(lectureAlert.ids==[l2] && lectureAlert.actionable,"Single new lecture action")
history=try JSONDecoder().decode(ContentNotificationHistory.self,from:JSONEncoder().encode(history))
history.ingest(notificationSnapshot(noticeIDs:[n2,n1],lectureIDs:[l2,l1]),notices:true,lectures:true)
expect(history.alerts.count==2,"Reordering and relaunch do not duplicate alerts")
history.ingest(notificationSnapshot(noticeIDs:[],lectureIDs:nil),notices:true,lectures:true)
history.ingest(notificationSnapshot(noticeIDs:[n1,n2],lectureIDs:[l1,l2]),notices:true,lectures:true)
expect(history.alerts.count==2,"Deletion, partial failure and reappearance do not repeat")
expect(history.eligibleIDs(for:lectureAlert,in:notificationSnapshot(lectureIDs:[l2],blocked:[l2])).isEmpty,"Expired or completed lecture cannot start")
expect(history.eligibleIDs(for:lectureAlert,in:notificationSnapshot(account:"other",lectureIDs:[l2])).isEmpty,"Account mismatch cannot start")
expect(history.eligibleIDs(for:lectureAlert,in:notificationSnapshot(term:"2027,1",lectureIDs:[l2])).isEmpty,"Term mismatch cannot start")
history.markDelivered(lectureAlert.id)
expect(history.pending(account:"account-a",notices:false,lectures:true).isEmpty,"Delivered notifications are not retried")
let count=history.alerts.count
history.ingest(notificationSnapshot(account:"other",noticeIDs:[n1,n2],lectureIDs:[l1,l2]),notices:true,lectures:true)
expect(history.alerts.count==count,"New account baseline is isolated")
history.ingest(notificationSnapshot(courses:["c1","c2"],noticeIDs:[n1,n2,contentID("notice","c2","1")],lectureIDs:[l1,l2]),notices:true,lectures:true)
expect(history.alerts.count==count,"New course baseline avoids old content notifications")
let l3=contentID("lecture","c1","3"),l4=contentID("lecture","c2","2")
history.ingest(notificationSnapshot(courses:["c1","c2"],noticeIDs:[n1,n2],lectureIDs:[l1,l2,l3,l4]),notices:true,lectures:true)
expect(Set(history.alerts.last!.ids)==Set([l3,l4]),"Multiple courses combine into one attend-all alert")
history.ingest(notificationSnapshot(lectureIDs:[l1,l2,l3,contentID("lecture","c1","5")]),notices:false,lectures:false)
let mutedCount=history.alerts.count
history.ingest(notificationSnapshot(lectureIDs:[l1,l2,l3,contentID("lecture","c1","5")]),notices:true,lectures:true)
expect(history.alerts.count==mutedCount,"Reenable does not replay muted additions")
expect(ContentAddress("lecture:v1:!:!:!") == nil && ContentAddress("1:2")==nil,"Malformed and legacy IDs rejected")
expect(history.alert(lectureAlert.id,now:Date().addingTimeInterval(15*86400))==nil,"Old notification actions expire")
let unicodeAddress=ContentAddress(contentID("lecture","과목 🚀","강의/ID","2026,2"))
expect(unicodeAddress?.term == "2026,2" && unicodeAddress?.course == "과목 🚀" && unicodeAddress?.parts == ["강의/ID"],"Unicode and URL-safe base64 identities round-trip")
expect(ContentAddress("lecture:v1:a:a:a:extra")==nil,"Extra identity fields rejected")
expect(ContentAddress("notice:v1:a:a:a")==nil,"Incomplete notice identity rejected")
expect(ContentAddress("lecture:v1:!:a:a")==nil,"Malformed base64 rejected")
var expiringHistory=ContentNotificationHistory()
expiringHistory.ingest(notificationSnapshot(noticeIDs:[n1],lectureIDs:[l1]),notices:true,lectures:true,now:baseDate)
expiringHistory.ingest(notificationSnapshot(noticeIDs:[n1,n2],lectureIDs:[l1,l2]),notices:true,lectures:true,now:baseDate.addingTimeInterval(1))
let expiringAlert=expiringHistory.alerts.first{$0.kind == .lecture}!
expect(expiringHistory.alert(expiringAlert.id,now:expiringAlert.created.addingTimeInterval(14*86400)) != nil,"Alert remains actionable at the exact expiry boundary")
expiringHistory.ingest(notificationSnapshot(noticeIDs:[n1,n2],lectureIDs:[l1,l2]),notices:true,lectures:true,now:expiringAlert.created.addingTimeInterval(14*86400+1))
expect(expiringHistory.alert(expiringAlert.id,now:expiringAlert.created.addingTimeInterval(14*86400+1)) == nil,"Expired alerts are pruned after the boundary")
var emptyAccountHistory=ContentNotificationHistory()
emptyAccountHistory.ingest(notificationSnapshot(account:"",noticeIDs:[n1],lectureIDs:[l1]),notices:true,lectures:true,now:baseDate)
expect(emptyAccountHistory.alerts.isEmpty,"Snapshot without an account cannot create notifications")
print("24 content notification checks passed")
