import KLAPCore
import Foundation
import CoreGraphics
func expect(_ condition: @autoclosure () -> Bool, _ message: String) {
    guard condition() else { fatalError(message) }
}
expect(StudyProgress(percent: -2, current: -1, total: -1) == StudyProgress(percent: 0, current: 0, total: 0), "Negative values")
expect(StudyProgress(percent: 150, current: 9, total: 3).fraction == 1, "Upper bound")
expect(StudyProgress(percent: .nan, current: 1, total: 3).fraction == 0, "NaN")
expect(StudyProgress(percent: .infinity, current: 1, total: 3).fraction == 0, "Infinity")
expect(StudyProgress(percent: 35, current: 2, total: 5).label == "2/5", "Queue position")
expect(StudyProgress(percent: 0, current: 1, total: 0).label == "", "Empty queue")
expect(StudyProgress(percent: 0, current: 8, total: 5).label == "5/5", "Queue clamp")
print("7 progress checks passed")
expect(TimetableClock.minutes(period: -1, span: 1) == nil, "Negative period")
expect(TimetableClock.minutes(period: 1, span: 0) == nil, "Invalid span")
expect(TimetableClock.minutes(period: 11, span: 2) == nil, "Overflow period")
expect(TimetableClock.minutes(period: 0, span: 2)?.end == 590, "Special consecutive class")
expect(TimetableClock.minutes(period: 6, span: 3)?.end == 1155, "Evening consecutive class")
expect(TimetableClock.minutes(period: 11, span: 1)?.end == 1325, "Night class")
expect(DestinationPolicy.uniqueNames(["A","A","B"," "]) == ["B"], "Ambiguous destinations")
expect(DestinationPolicy.uniqueNames([]).isEmpty, "Empty destinations")
expect(DestinationPolicy.availableName("KLAP",existing:["KLAP","KLAP (2)"]) == "KLAP (3)", "New destination collisions")
expect(DestinationPolicy.availableName("KLAP",existing:[]) == "KLAP", "First destination")
print("10 timetable and destination checks passed")

func makeEntry(_ period:Int, _ span:Int=1, day:Int=1, online:Bool=false) throws -> TimetableEntry {
    let data=try JSONSerialization.data(withJSONObject:["SubjectID":"course", "SubjectName":"과목", "Weekday":day, "Period":period, "Span":span, "Room":"101", "Online":online])
    return try JSONDecoder().decode(TimetableEntry.self,from:data)
}
let layout=TimetableClock.placements(try [makeEntry(0),makeEntry(1),makeEntry(2)])
expect(layout.map(\.lane) == [0,1,1], "Overlapping intervals reuse only free lanes")
expect(layout.allSatisfy{$0.laneCount == 2}, "Consistent overlapping lane widths")
let excluded = try [makeEntry(1,day:0),makeEntry(2,online:true)]
expect(TimetableClock.placements(excluded).isEmpty,"Unknown and online classes excluded from grid")
let empty=try JSONDecoder().decode(Snapshot.self,from:Data("{\"timetable\":null,\"lectures\":null,\"errors\":[]}".utf8))
expect(empty.lectures == nil && empty.errors.isEmpty,"Nullable CLI collections")
print("4 layout and decoding checks passed")
let screen = CGRect(x:0,y:0,width:1440,height:875)
let rightPanel=MenuPanelPlacement.frame(anchor:CGRect(x:1410,y:875,width:24,height:25),visibleScreen:screen,size:CGSize(width:540,height:700))
expect(screen.contains(rightPanel) && rightPanel.maxX == 1432, "Panel remains inside right edge")
let leftScreen=CGRect(x:-1920,y:0,width:1920,height:1055)
let leftPanel=MenuPanelPlacement.frame(anchor:CGRect(x:-1910,y:1055,width:24,height:25),visibleScreen:leftScreen,size:CGSize(width:540,height:700))
expect(leftScreen.contains(leftPanel) && leftPanel.minX == -1912,"Secondary monitor with negative origin")
let smallScreen=CGRect(x:0,y:0,width:500,height:600)
let smallPanel=MenuPanelPlacement.frame(anchor:CGRect(x:250,y:600,width:24,height:25),visibleScreen:smallScreen,size:CGSize(width:540,height:700))
expect(smallScreen.contains(smallPanel),"Small screen bounds")
print("3 panel positioning checks passed")

expect(StudyTime(achieved:"5",required:"20").remaining == 15,"Remaining minutes")
expect(StudyTime(achieved:"30",required:"20").remaining == 0,"Over-completed clamp")
expect(StudyTime(achieved:nil,required:"20").remaining == nil,"Unknown achieved")
expect(StudyTime(achieved:"NaN",required:"20").remaining == nil,"Invalid achieved")
expect(StudyTime(achieved:"2",required:"0").remaining == nil,"Unknown duration")
expect(StudyTime(achieved:"-1",required:"20").remaining == nil,"Negative achieved")
expect(StudyTime.minutes(0.5) == "1분","Round remaining up")
print("7 study time checks passed")

let reminderNote="--- KLAP ---\nID: lecture:abc\n[This reminder is created by KLAP.]"
expect(ReminderIdentity.matches(notes:reminderNote,lectureID:"abc"),"Exact lecture ID")
expect(ReminderIdentity.matches(notes:reminderNote,lectureID:"lecture:abc"),"Prefixed lecture ID")
expect(!ReminderIdentity.matches(notes:reminderNote,lectureID:"ab"),"No prefix collision")
expect(!ReminderIdentity.matches(notes:"ID: lecture:abc",lectureID:"abc"),"No unowned reminder")
expect(!ReminderIdentity.matches(notes:nil,lectureID:"abc"),"Missing metadata")
expect(!ReminderIdentity.matches(notes:reminderNote,lectureID:""),"Empty identity")
print("6 reminder identity checks passed")

let fullScreen=CGRect(x:0,y:0,width:1440,height:900)
expect(!MenuPanelPlacement.validAnchor(.zero,screen:fullScreen),"Unlaid status item")
expect(!MenuPanelPlacement.validAnchor(CGRect(x:0,y:0,width:24,height:24),screen:fullScreen),"Temporary origin rejected")
expect(MenuPanelPlacement.validAnchor(CGRect(x:1200,y:875,width:24,height:25),screen:fullScreen),"Menu bar anchor accepted")
expect(MenuPanelPlacement.validAnchor(CGRect(x:-1200,y:875,width:24,height:25),screen:CGRect(x:-1440,y:0,width:1440,height:900)),"Negative screen anchor accepted")
expect(!MenuPanelPlacement.validAnchor(CGRect(x:1600,y:875,width:24,height:25),screen:fullScreen),"Wrong screen rejected")
print("5 startup anchor checks passed")

let tones=CourseTones.assign(["a","b","c","d","e","a"])
expect(tones.count == 5 && Set(tones.values).count == 5,"Distinct tones for five courses")
expect(tones == CourseTones.assign(["e","d","c","b","a"]),"Stable order and repeated meetings")
expect(CourseTones.assign([]).isEmpty,"Empty course palette")
expect(CourseTones.assign(["one"])["one"] == 50,"Single course seed")
expect(Set(CourseTones.assign((0..<20).map(String.init)).values).count == 20,"No modulo palette collisions")
print("5 course tone checks passed")

let deadline=Date(timeIntervalSince1970:100000)
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:nil,finished:deadline,now:deadline) == .complete,"Completed at deadline")
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:deadline.addingTimeInterval(-1),finished:deadline.addingTimeInterval(1),now:deadline) == .late,"Crossed deadline")
expect(LectureStatus.resolve(complete:true,deadline:deadline,started:nil,finished:nil,now:deadline.addingTimeInterval(1)) == .unknown,"No invented completion time")
expect(LectureStatus.resolve(complete:false,deadline:deadline,started:nil,finished:nil,now:deadline.addingTimeInterval(1)) == .missed,"Expired incomplete")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-18000)) == 2,"Five hours red")
expect(LectureStatus.urgency(deadline:deadline,now:deadline.addingTimeInterval(-86400)) == 1,"One day orange")
print("6 lecture status checks passed")

let serverLecture = try JSONDecoder().decode(Lecture.self,from:Data(#"{"Title":"sample","Progress":"100","FirstStartedAt":"2026-09-01T15:01:00+09:00","FirstCompletedAt":"2026-09-01T16:33:00+09:00","AchievedTime":"41","RequiredTime":"41","EndAt":"2026-09-14T23:59:00+09:00"}"#.utf8))
expect(LectureStatus.date(serverLecture.FirstStartedAt) != nil && LectureStatus.date(serverLecture.FirstCompletedAt) != nil,"CLI server timestamps decode")
let legacyLecture=try JSONDecoder().decode(Lecture.self,from:Data(#"{"Title":"sample","Progress":"0"}"#.utf8))
expect(legacyLecture.FirstStartedAt == nil && legacyLecture.FirstCompletedAt == nil,"Older cache timestamps unknown")
print("2 CLI timestamp contract checks passed")

let periodRows=TimetableClock.placements(try [makeEntry(1),makeEntry(1,2),makeEntry(3)],byPeriod:true)
expect(periodRows.map(\.start) == [1,1,3],"Period grid starts")
expect(periodRows.map(\.end) == [2,3,4],"Period spans preserved")
expect(periodRows.map(\.lane) == [0,1,0],"Period overlaps and adjacency")
let nightRows=TimetableClock.placements(try [makeEntry(11)],byPeriod:true)
expect(nightRows.first?.end == 12,"Last period boundary")
let onlineRows=TimetableClock.placements(try [makeEntry(1,online:true)],byPeriod:true)
expect(onlineRows.isEmpty,"Online outside period grid")
print("5 period grid checks passed")
let minimalNotice = try JSONDecoder().decode(Notice.self, from: Data(#"{"Title":"공지"}"#.utf8))
expect(minimalNotice.Registered == nil && minimalNotice.Top == nil, "Older notice metadata")
let emptyNotice = try JSONDecoder().decode(NoticeDetailResult.self, from: Data(#"{"ID":"n","DetailURL":"https://klas.kw.ac.kr/","Detail":{"Title":"공지","ContentText":"","Registered":null,"Attachment":null}}"#.utf8))
expect(emptyNotice.Detail.ContentText.isEmpty && emptyNotice.Detail.Attachment == nil, "Empty notice body and null attachment")
print("2 notice contract checks passed")
expect(GradeAllocation(count:0) == nil && GradeAllocation(count:-1) == nil, "Unknown or empty enrollment")
let allocation107 = GradeAllocation(count:107)!
expect(allocation107.a == 42 && allocation107.b == 43 && allocation107.lower == 22, "Noncumulative grade example")
for count in [1, 20, 21, 100, 107, Int.max] {
    let value = GradeAllocation(count:count)!
    expect(value.a + value.b + value.lower == count, "Allocation conserves enrollment")
    expect(value.a >= 0 && value.b >= 0 && value.lower >= 0, "Allocation nonnegative")
}
print("14 grade allocation checks passed")

let previewTestRoot=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
defer { try? FileManager.default.removeItem(at:previewTestRoot) }
let previewRoot=previewTestRoot.appendingPathComponent("cache")
let downloadsRoot=previewTestRoot.appendingPathComponent("downloads")
let baseDate=Date()
var store=try PreviewFileStore(root:previewRoot,now:baseDate)
func samplePreview(_ name:String) throws -> URL {
    let folder=previewRoot.appendingPathComponent("attachment-"+UUID().uuidString)
    try FileManager.default.createDirectory(at:folder,withIntermediateDirectories:true)
    let file=folder.appendingPathComponent(name); try Data("PDF".utf8).write(to:file); return file
}
let first=try samplePreview("자료.pdf")
try store.register(first,key:"one",now:baseDate)
try store.opened("one")
try store.cleanup(now:baseDate.addingTimeInterval(20000))
expect(FileManager.default.fileExists(atPath:first.path),"Open preview never expires")
try store.closed("one",now:baseDate)
try store.cleanup(now:baseDate.addingTimeInterval(10799))
expect(FileManager.default.fileExists(atPath:first.path),"Preserve before three hours")
try store.cleanup(now:baseDate.addingTimeInterval(10800))
expect(!FileManager.default.fileExists(atPath:first.path),"Delete at three hours")
let second=try samplePreview("資料.pdf")
try store.register(second,key:"two",now:baseDate)
store=try PreviewFileStore(root:previewRoot,now:baseDate.addingTimeInterval(100))
let cachedSecond = try store.cached("two",now:baseDate.addingTimeInterval(100))
expect(cachedSecond == second,"Persist cache across launch")
try FileManager.default.createDirectory(at:downloadsRoot,withIntermediateDirectories:true)
try Data("existing".utf8).write(to:downloadsRoot.appendingPathComponent("資料.pdf"))
let saved=try store.moveToDownloads("two",directory:downloadsRoot,now:baseDate.addingTimeInterval(100))
expect(saved.lastPathComponent == "資料 (1).pdf","Preserve duplicate filename")
expect(!FileManager.default.fileExists(atPath:second.path),"Move instead of copy")
try store.cleanup(now:baseDate.addingTimeInterval(30000))
expect(FileManager.default.fileExists(atPath:saved.path),"Downloads excluded from cleanup")
let originalDownload = try Data(contentsOf:downloadsRoot.appendingPathComponent("資料.pdf"))
expect(originalDownload == Data("existing".utf8),"Existing download unchanged")
let third=try samplePreview("image.png")
try store.register(third,key:"three",now:baseDate)
try store.opened("three"); try store.closed("three",now:baseDate)
try store.opened("three"); try store.closed("three",now:baseDate.addingTimeInterval(1000))
try store.cleanup(now:baseDate.addingTimeInterval(10800))
expect(FileManager.default.fileExists(atPath:third.path),"Reopen resets close deadline")
store=try PreviewFileStore(root:previewRoot,now:baseDate.addingTimeInterval(11800))
expect(!FileManager.default.fileExists(atPath:third.path),"Expired cache cleaned on launch")
do { try store.register(saved,key:"outside"); fatalError("Accepted external file") } catch { }
print("11 preview file lifecycle checks passed")

let linkedText="한글 안내 👋\nhttps://discord.gg/3vv49s3UJ\n자세한 내용: (https://example.org/docs?q=1&lang=ko)."
let linked=LinkedBody.attributed(linkedText)
let urls=linked.runs.compactMap { $0.link?.absoluteString }
expect(String(linked.characters)==linkedText,"Link detection preserves Korean, emoji and line breaks")
expect(urls==["https://discord.gg/3vv49s3UJ","https://example.org/docs?q=1&lang=ko"],"Detect URLs without surrounding punctuation")
expect(LinkedBody.attributed("").runs.compactMap(\.link).isEmpty,"Empty body")
expect(LinkedBody.attributed("일반 공지입니다").runs.compactMap(\.link).isEmpty,"Plain body")
expect(LinkedBody.attributed("javascript:alert(1) file:///tmp/a").runs.compactMap(\.link).isEmpty,"Do not make executable or local URLs clickable")
print("5 body link checks passed")

let memory=MemoryPreviewStore(limit:8)
try memory.register(Data([1,2,3,4]),name:"../sample.pdf",key:"one")
memory.opened("one")
try memory.register(Data([5,6,7,8]),name:"sample.pdf",key:"two")
try memory.register(Data([9,10,11,12]),name:"sample.pdf",key:"three")
expect(memory.cached("one") != nil && memory.cached("two")==nil,"Eviction protects open previews")
do {try memory.register(Data(repeating:0,count:9),name:"large",key:"large");fatalError("Accepted oversized preview")} catch {}
expect(memory.byteCount==8,"Oversize rejection preserves cache")
let memoryDownloads=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
defer {try? FileManager.default.removeItem(at:memoryDownloads)}
let memoryFirst=try memory.save("one",to:memoryDownloads)
let memorySecond=try memory.save("three",to:memoryDownloads)
expect(memoryFirst.lastPathComponent=="sample.pdf" && memorySecond.lastPathComponent=="sample (1).pdf","Sanitize paths and preserve duplicate downloads")
let memorySavedBytes=try Data(contentsOf:memoryFirst)
expect(memorySavedBytes==Data([1,2,3,4]),"Downloaded bytes unchanged")
expect(memory.byteCount==0,"Download releases cached data")
try memory.register(Data([1]),name:"expiry",key:"expiry",now:baseDate)
memory.opened("expiry")
memory.cleanup(now:baseDate.addingTimeInterval(20000))
expect(memory.cached("expiry") != nil,"Open preview does not expire")
memory.closed("expiry",now:baseDate)
memory.cleanup(now:baseDate.addingTimeInterval(10800))
expect(memory.cached("expiry")==nil,"Closed preview expires after three hours")
print("7 memory preview checks passed")
