import Foundation
var state=LectureDownloadState()
state.begin(["a","a","b","c"])
precondition(state.expected == ["a","b","c"] && state.rows.count==3)
state.apply(.init(ID:"unknown",Stage:"done",Bytes:1,TotalBytes:1,Error:""))
precondition(state.rows.count==3)
state.apply(.init(ID:"a",Stage:"download",Bytes:200,TotalBytes:100,Error:""))
precondition(state.rows["a"]?.fraction==1)
state.apply(.init(ID:"b",Stage:"download",Bytes:-1,TotalBytes:0,Error:""))
precondition(state.rows["b"]?.bytes==0 && state.rows["b"]?.fraction==nil)
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:100,Skipped:false,Error:""),.init(ID:"b",Path:"",Bytes:0,Skipped:false,Error:"지원하지 않음")])
state.finish(error:nil,receivedResult:true)
precondition(state.completed==1 && state.retryIDs == ["b","c"] && !state.running)
state.begin(["a"])
state.apply(.init(ID:"a",Stage:"done",Bytes:1,TotalBytes:1,Error:""))
state.finish(error:nil,receivedResult:false)
precondition(state.failure != nil && state.completed==0 && state.retryIDs == ["a"])
state.begin(["a","b"])
state.cancelling=true
state.finish(error:"terminated",receivedResult:false)
precondition(state.failure==nil && state.rows.values.allSatisfy{$0.stage == "cancelled"})
state.begin(["a"])
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:100,Skipped:true,Error:"")])
state.finish(error:nil,receivedResult:true)
precondition(state.completed==1 && state.rows["a"]?.label == "이미 다운로드됨")
print("Download deduplication, progress bounds, unknown IDs, partial/missing results, cancellation and retry checks passed")
state.begin(["a","b"])
let progress=try JSONDecoder().decode(LectureDownloadProgressData.self,from:Data(#"{"ID":"a","Stage":"done","Path":"/tmp/a.mp4","Bytes":100,"TotalBytes":100,"Error":""}"#.utf8))
state.apply(progress)
precondition(state.completed==1 && state.rows["a"]?.path=="/tmp/a.mp4")
state.cancelling=true
state.finish(error:"terminated",receivedResult:false)
precondition(state.rows["a"]?.finished==true && state.rows["b"]?.stage=="cancelled")
print("Completed file progress and cancellation preserve finished downloads")
state.begin(["a","b","c"])
state.apply(.init(ID:"a",Stage:"download",Bytes:50,TotalBytes:100,Error:""))
state.apply(.init(ID:"b",Stage:"paused",Bytes:25,TotalBytes:100,Error:""))
precondition(state.active==1 && state.paused==1 && state.fraction==0.25)
precondition(state.rows["b"]?.label.contains("일시정지")==true)
state.apply(LectureTranscriptProgressData(ID:"a",Stage:"transcribed",Path:"/tmp/a.txt",Error:""))
state.apply(LectureTranscriptProgressData(ID:"unknown",Stage:"transcribed",Path:"/tmp/x.txt",Error:""))
precondition(state.transcripts.count==1 && state.rows["a"]?.stage=="download")
state.begin([])
precondition(state.fraction==0 && state.transcripts.isEmpty && state.active==0)
print("Adaptive pause, aggregate progress, transcript isolation and empty queue checks passed")

for base in ["/Users/example/Downloads","/tmp/한글 폴더","/tmp/base/../선택한 폴더"] {
    let selected=URL(fileURLWithPath:base,isDirectory:true)
    let root=LectureDownloadLocation.root(in:selected)
    precondition(root.path==selected.standardizedFileURL.path+"/KLAP")
    precondition(root.appendingPathComponent("자료구조/Video").path==selected.standardizedFileURL.path+"/KLAP/자료구조/Video")
}
print("Selected base folder and KLAP/course/Video path checks passed")
