import Foundation
var state=LectureDownloadState()
state.begin(["a","a","b","c"])
precondition(state.expected == ["a","b","c"] && state.rows.count==3)
state.apply(.init(ID:"unknown",Stage:"done",Bytes:1,TotalBytes:1,Error:""))
precondition(state.rows.count==3)
state.apply(.init(ID:"a",Stage:"download",Bytes:200,TotalBytes:100,Error:""))
precondition(state.rows["a"]?.fraction==1)
state.apply(.init(ID:"b",Stage:"download",Bytes:-1,TotalBytes:0,Error:""))
precondition(state.rows["b"]?.bytes==0 && state.rows["b"]?.fraction==nil)
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:100,Skipped:false,Error:""),.init(ID:"b",Path:"",Bytes:0,Skipped:false,Error:"지원하지 않음")])
state.finish(error:nil,receivedResult:true)
precondition(state.completed==1 && state.retryIDs == ["b","c"] && !state.running)
state.begin(["a"])
state.apply(.init(ID:"a",Stage:"done",Bytes:1,TotalBytes:1,Error:""))
state.finish(error:nil,receivedResult:false)
precondition(state.failure != nil && state.completed==0 && state.retryIDs == ["a"])
state.begin(["a","b"])
state.cancelling=true
state.finish(error:"terminated",receivedResult:false)
precondition(state.failure==nil && state.rows.values.allSatisfy{$0.stage == "cancelled"})
state.begin(["a"])
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:100,Skipped:true,Error:"")])
state.finish(error:nil,receivedResult:true)
precondition(state.completed==1 && state.rows["a"]?.label == "이미 다운로드됨")
print("Download deduplication, progress bounds, unknown IDs, partial/missing results, cancellation and retry checks passed")
state.begin(["a","b"])
let progress=try JSONDecoder().decode(LectureDownloadProgressData.self,from:Data(#"{"ID":"a","Stage":"done","Path":"/tmp/a.mp4","Bytes":100,"TotalBytes":100,"Error":""}"#.utf8))
state.apply(progress)
precondition(state.completed==1 && state.rows["a"]?.path=="/tmp/a.mp4")
state.cancelling=true
state.finish(error:"terminated",receivedResult:false)
precondition(state.rows["a"]?.finished==true && state.rows["b"]?.stage=="cancelled")
print("Completed file progress and cancellation preserve finished downloads")
state.begin(["a","b","c"])
state.apply(.init(ID:"a",Stage:"download",Bytes:50,TotalBytes:100,Error:""))
state.apply(.init(ID:"b",Stage:"paused",Bytes:25,TotalBytes:100,Error:""))
precondition(state.active==1 && state.paused==1 && state.fraction==0.25)
precondition(state.rows["b"]?.label.contains("일시정지")==true)
state.apply(LectureTranscriptProgressData(ID:"a",Stage:"transcribed",Path:"/tmp/a.txt",Error:""))
state.apply(LectureTranscriptProgressData(ID:"unknown",Stage:"transcribed",Path:"/tmp/x.txt",Error:""))
precondition(state.transcripts.count==1 && state.rows["a"]?.stage=="download")
state.begin([])
precondition(state.fraction==0 && state.transcripts.isEmpty && state.active==0)
print("Adaptive pause, aggregate progress, transcript isolation and empty queue checks passed")

for base in ["/Users/example/Downloads","/tmp/한글 폴더","/tmp/base/../선택한 폴더"] {
    let selected=URL(fileURLWithPath:base,isDirectory:true)
    let root=LectureDownloadLocation.root(in:selected)
    precondition(root.path==selected.standardizedFileURL.path+"/KLAP")
    precondition(root.appendingPathComponent("자료구조/Videos").path==selected.standardizedFileURL.path+"/KLAP/자료구조/Videos")
}
print("Selected base folder and KLAP/course/Videos path checks passed")

state.begin(["finished","active","failed"])
state.apply(.init(ID:"finished",Stage:"done",Bytes:10,TotalBytes:10,Error:"",Path:"/tmp/finished.mp4"))
state.apply(.init(ID:"failed",Stage:"error",Bytes:0,TotalBytes:0,Error:"network failure"))
state.cancelling=true
state.apply(.init(ID:"active",Stage:"error",Bytes:5,TotalBytes:10,Error:"terminated signal received"))
state.apply(LectureTranscriptProgressData(ID:"finished",Stage:"transcript-error",Path:"",Error:"terminated signal received"))
state.finish(error:"terminated",receivedResult:false)
precondition(state.rows["active"]?.stage=="cancelled" && state.rows["active"]?.error==nil && state.failure==nil)
precondition(state.rows["finished"]?.finished==true && state.rows["failed"]?.error=="network failure")
precondition(state.transcripts["finished"]?.Stage=="cancelled" && state.transcripts["finished"]?.Error=="")
print("Cancellation errors are neutral while earlier real failures and completed files remain intact")

state.begin(["a"])
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:10,Skipped:true,Error:"")])
state.apply(LectureTranscriptProgressData(ID:"a",Stage:"transcribe",Path:"",Error:""))
state.cancelling=true
state.finish(error:"killed before final event",receivedResult:false)
precondition(state.transcripts["a"]?.Stage=="cancelled" && state.transcripts["a"]?.Error=="")
precondition(state.rows["a"]?.finished==true && state.failure==nil)
print("Cancellation without a final transcript event preserves the video and clears transient status")
state.begin(["a","b"])
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:100,Skipped:false,Error:""),.init(ID:"b",Path:"/tmp/b.mp4",Bytes:100,Skipped:false,Error:"")])
precondition(state.displayCurrent==2 && state.displayTotal==2 && state.displayFraction==1)
state.downloadPhaseFinished=true
state.beginTranscription(["a","a","b","unknown"])
state.apply(LectureTranscriptProgressData(ID:"a",Stage:"transcribe",Path:"",Error:"",Progress:0.5))
precondition(state.transcribing && state.displayCurrent==1 && state.displayTotal==2 && state.displayFraction==0.25)
state.apply(LectureTranscriptProgressData(ID:"a",Stage:"transcribed",Path:"/tmp/a.txt",Error:""))
state.apply(LectureTranscriptProgressData(ID:"b",Stage:"transcribe",Path:"",Error:"",Progress:0.2))
precondition(state.displayCurrent==2 && state.displayFraction==0.6)
state.apply(LectureTranscriptProgressData(ID:"b",Stage:"transcript-error",Path:"",Error:"failed"))
precondition(state.displayFraction==1)
state.begin([])
precondition(!state.transcribing && state.displayTotal==0 && state.displayFraction==0)
print("Download-to-transcript phase, queue deduplication, fraction and failure progress checks passed")

state.begin(["unsupported"])
state.apply(.init(ID:"unsupported",Stage:"skip",Bytes:0,TotalBytes:0,Error:"KWCommons 콘텐츠 ID가 없습니다"))
precondition(state.completed==0 && state.rows["unsupported"]?.stage=="error")
state.apply(.init(ID:"unsupported",Stage:"done",Bytes:0,TotalBytes:0,Error:""))
precondition(state.completed==0)
print("Skipped unsupported lectures and missing file paths never count as downloaded")

state.begin(["a","b"])
state.apply([.init(ID:"a",Path:"/tmp/a.mp4",Bytes:100,Skipped:false,Error:"")])
state.beginTranscription(["a"])
state.apply(LectureTranscriptProgressData(ID:"a",Stage:"transcribe",Path:"",Error:"",Progress:0.2))
precondition(!state.transcribing && state.displayCurrent==1 && state.displayTotal==2 && state.displayFraction==0.5)
precondition(state.transcriptCurrent==1 && state.transcriptFraction==0.2)
state.beginTranscription(["a","b"])
state.apply(LectureTranscriptProgressData(ID:"b",Stage:"transcript-waiting",Path:"",Error:""))
precondition(state.transcriptCurrent==1)
state.downloadPhaseFinished=true
precondition(state.transcribing && state.displayCurrent==1 && state.displayTotal==2 && state.displayFraction==0.1)
state.cancelling=true;state.finish(error:nil,receivedResult:false)
precondition(state.transcripts["b"]?.Stage=="cancelled")
print("Concurrent transcription preserves download display priority and distinguishes queued work")
